[project]
name = 'xStrata'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = 2.5

# Your "main" contract (as you had it)
[contracts.inscription]
path = 'contracts/u64bxr-v11.1.clar'
clarity_version = 4
epoch = 'latest'

# Add every other contract so Clarinet checks them too
[contracts.u64bxr-v7]
path = 'contracts/u64bxr-v7.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v8]
path = 'contracts/u64bxr-v8.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v9]
path = 'contracts/u64bxr-v9.clar'
clarity_version = 4
epoch = 'latest'

# File has a dot, but contract name must not.
[contracts.u64bxr-v9-2]
path = 'contracts/u64bxr-v9.2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v11]
path = 'contracts/u64bxr-v11.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v11-1]
path = 'contracts/u64bxr-v11.1.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v11-2]
path = 'contracts/u64bxr-v11.2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.u64bxr-v11-3]
path = 'contracts/u64bxr-v11.3.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = [
  'call_checker',
  'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
