[project]
name = 'xtrata'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.xtrata-v1-1-0]
path = 'contracts/xtrata-v1.1.0.clar'
clarity_version = 3
epoch = 'latest'


[repl.analysis]
passes = [
  'call_checker',
  'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
